[project]
name = "mcp9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.16.0",
    "openai-agents>=0.3.3",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
