[project]
name = "mcp3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.15.0",
    "prompt-toolkit>=3.0.52",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
]
